Support deriving node version from app.json or package.json

diff --git a/bin/start b/bin/start
--- a/bin/start
+++ b/bin/start
@@ -20,8 +20,7 @@ findFile() {
 # Find the package.json.
 PACKAGE_PATH=$(findFile "package.json" "./")
 
-# Attempt to read the main, start, and version from package.json.
-NODE_VERSION=$(get-version --engine node $PACKAGE_PATH)
+# Attempt to read the main and start from package.json.
 MAIN=$(node -pe "require('$PACKAGE_PATH').main || ''" 2> /dev/null || true)
 START=$(node -pe "require('$PACKAGE_PATH').scripts.start || ''" 2> /dev/null || true)
 
@@ -81,6 +80,19 @@ fi
 
 # Install node
 NVM_DIR=$HOME/.nvm
+
+# support deriving node version from app.json or package.json
+if [ -f /mnt/app/app.json ] && [[ $MODULUS_CONFIG_ENGINES_NODE || $MODULUS_CONFIG_ENGINES_IOJS ]]; then
+  SOURCE_PATH=/mnt/app/app.json
+else
+  SOURCE_PATH=$PACKAGE_PATH
+fi
+
+NODE_VERSION=$(get-version --engine node $SOURCE_PATH)
+if [[ ! $NODE_VERSION ]]; then
+  printf "Unable to determine node version.\n"
+  exit 1
+fi
 
 echo "INFO: Initializing Node.js v$NODE_VERSION."
 nvm install $NODE_VERSION &> /dev/null
